### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by dpdclub** [phydev/angio#3]
Dear Authors,

Thank you for sharing this interesting project. I was trying to run this code, but also got error either from pulling the docker file or compile the src. The error messages are attached.  Could you please provide some suggestions.  Thanks,

```
 docker build --platform linux/x86_64 -t angio docker/
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping"                           : dial unix /var/run/docker.sock: connect: permission denied

```

 ```
./compile.sh
ifort: command line remark #10412: option '-mkl' is deprecated and will be removed in a future release. Please use the replacement option '-qmkl'
./src/run_angio.F90(171): error #6633: The type of the actual argument differs from the type of the dummy argument.   [PERIODIC]
      vegf_c, nstep, vegf_grad_min, np, cell_radius, n_max_tipc, np_tip_s, periodic)
---------------------------------------------------------------------------^
./src/run_angio.F90(170): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [VEGF_XYZ]
      call etc_search(cell, tipc, gg, Lsize, lxyz, lxyz_inv, notch_distance, n_tipcell, tip_s, &
-----------^
./src/run_angio.F90(170): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [NDIM]
      call etc_search(cell, tipc, gg, Lsize, lxyz, lxyz_inv, notch_distance, n_tipcell, tip_s, &
-----------^
./src/run_angio.F90(170): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [PERIODIC]
      call etc_search(cell, tipc, gg, Lsize, lxyz, lxyz_inv, notch_distance, n_tipcell, tip_s, &
-----------^
./src/run_angio.F90(171): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [PERIODIC]
      vegf_c, nstep, vegf_grad_min, np, cell_radius, n_max_tipc, np_tip_s, periodic)
---------------------------------------------------------------------------^
./src/run_angio.F90(170): error #8284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type character or is an element of an array that is not assumed shape, pointer, or polymorphic.   [GRID_CELL_DOMAIN]
      call etc_search(cell, tipc, gg, Lsize, lxyz, lxyz_inv, notch_distance, n_tipcell, tip_s, &
-----------^
./src/run_angio.F90(171): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [PERIODIC]
      vegf_c, nstep, vegf_grad_min, np, cell_radius, n_max_tipc, np_tip_s, periodic)
---------------------------------------------------------------------------^
compilation aborted for ./src/run_angio.F90 (code 1)
./src/main.F90(3): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [RUN_ANGIO_M]
  use run_angio_m
------^
compilation aborted for ./src/main.F90 (code 1)


```

**Comment by phydev** [comment]
Hi,

Thank you for your interest on our code.

I can see you are using `compile.sh` which calls `ifort` as compiler. The errors you are seeing are likely due to conflicts between the standard implemented in `ifort` at the time I wrote the script (almost 10 years ago) and the current version in your computer.  I'm going to remove the script from the repository since I cannot provide support for `ifort`.

Recently, we provided a [`Dockerfile`](https://github.com/phydev/angio/blob/master/docker/Dockerfile) for compiling our code with `gfortran`. I advise you to use it instead of `compile.sh`, as it was tested in our CI/CD workflow and worked fine. Check also the script [`run.sh`](https://github.com/phydev/angio/blob/master/run.sh).

If you have further issues please let me know.

Best regards,

Maurício.

**Comment by phydev** [comment]
The dockerized solution with `gfortran` is working (see the workflow [log](https://github.com/phydev/angio/actions/runs/8711467853/job/23895616965) for details).

**Comment by phydev** [comment]
Sorry, I saw that you also tried running the docker:

` docker build --platform linux/x86_64 -t angio docker/
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping"                           : dial unix /var/run/docker.sock: connect: permission denied
`

This error is implies that you need admin privileges to run docker in your computer. You can try to run the command with `sudo` before the command:

`sudo docker build --platform linux/x86_64 -t angio docker/` 

This solution, however, implies granting administrative rights to the Docker process, which might not be considered secure in certain situations. I cannot provide further suggestion without more information about your computer.

**Comment by dpdclub** [comment]
Hi Mauricio,

Thanks for your fast response.  It works right now.

He
________________________________

**Comment by dpdclub** [comment]
Hi Mauricio,  

When I tried to postprocess the result folder 001, I followed the instruction to run ./run_get, but I always end up with errors of counld not find those files, but those files are actually in the folder, do you have any clue of why is happening. 
Thanks a lot,


:~/Desktop/tumor/angio-master/001$   ./run_get
 initial file, last_file, delta, dir_name:
10 50 10 001
 ---------------------------------------------------------
                       get_data_m module

  This program calculate the mean diameter and the
  the number of branches for each time step of a
  simulation and plot two graphs as a function of time.
 ---------------------------------------------------------
Calculating . . .
          10
wc: 001/phi: No such file or directory
wc: 10.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 10.xyz: No such file or directory
At line 88 of file run_get.F90 (unit = 10)
Fortran runtime error: Cannot open file '001/phis  10.xyz': No such file or directory
